#!/bin/bash
#set -x

GREP_OPT="-rnH --color=auto"
INC_FILES=""
EXC_FILES="tags"
EXC_DIRS=".svn .git"
DEBUG=0

usage() {
	APPNAME=`basename $0`
	echo "Usage: $APPNAME [OPTIONS] PATTERN [FILES...]" 1>&2
	echo ""
	echo " [OPTIONS]"
	echo "  -inc|--include <GLOB>"
	echo "  -exc|--exclude <GLOB>"
	echo "  -exd|--exclude-dir <GLOB>"
	echo "  --debug"
	echo "  --help"
	echo "  -* ... pass through to grep command"
	echo ""
	exit 1
}

# disable file name generation (globbing)
set -f

while [ "$#" -gt 0 ]; do
    case "$1" in
        '-inc' | '--include')
            [ "$#" -lt 2 ] && usage
            INC_FILES="$INC_FILES $2"
            shift
            ;;
        '-exc' | '--exclude')
            [ "$#" -lt 2 ] && usage
            EXC_FILES="$EXC_FILES $2"
            shift
            ;;
        '-exd' | '--exclude-dir')
            [ "$#" -lt 2 ] && usage
            EXC_DIRS="$EXC_DIRS $2"
            shift
            ;;
        '--debug') DEBUG=1
            ;;
        '--help') usage
            ;;
        -*) GREP_OPT="$GREP_OPT $1"
            ;;
        *) break
            ;;
    esac
    shift
done
[ $# -le 0 ] && usage

PATTERN=$1
shift
FILES=$@
for i in $INC_FILES; do INCLUDE="$INCLUDE --include=$i"; done
for i in $EXC_FILES; do EXCLUDE="$EXCLUDE --exclude=$i"; done
for i in $EXC_DIRS; do EXCLUDE_DIR="$EXCLUDE_DIR --exclude-dir=$i"; done
if [ $DEBUG -ne 0 ]; then
	echo "INCLUDE=$INCLUDE"
	echo "EXCLUDE=$EXCLUDE"
	echo "EXCLUDE_DIR=$EXCLUDE_DIR"
fi

GREP_OPT="$GREP_OPT $INCLUDE $EXCLUDE $EXCLUDE_DIR"
[ $DEBUG -ne 0 ] && echo "grep $GREP_OPT \"$PATTERN\" $FILES"
grep $GREP_OPT "$PATTERN" $FILES
